"""add_draft_send_error

Revision ID: 53ffc429a5b1
Revises: a1a8a121593b
Create Date: 2026-07-09 14:43:02.768537
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '53ffc429a5b1'
down_revision: Union[str, None] = 'a1a8a121593b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drafts', sa.Column('send_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drafts', 'send_error')
    # ### end Alembic commands ###
