"""add_ai_metadata_to_outputs

Revision ID: 5427824fe2cb
Revises: edef68288b74
Create Date: 2026-07-12 01:55:55.207852
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5427824fe2cb'
down_revision: Union[str, None] = 'edef68288b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drafts', sa.Column('ai_metadata', sa.Text(), nullable=True))
    op.add_column('emails', sa.Column('ai_metadata', sa.Text(), nullable=True))
    op.add_column('reminders', sa.Column('ai_metadata', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'ai_metadata')
    op.drop_column('emails', 'ai_metadata')
    op.drop_column('drafts', 'ai_metadata')
    # ### end Alembic commands ###
