"""add_email_attachments

Revision ID: 654289579ece
Revises: 53ffc429a5b1
Create Date: 2026-07-12 01:11:27.965735
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '654289579ece'
down_revision: Union[str, None] = '53ffc429a5b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('attachments', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'attachments')
    # ### end Alembic commands ###
