"""add_users

Revision ID: 6629166b3b5e
Revises: 951aabbdf27e
Create Date: 2026-07-08 13:30:04.794124
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '6629166b3b5e'
down_revision: Union[str, None] = '951aabbdf27e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
