"""add_spam_fields

Revision ID: 6b63f46afa3f
Revises: 5427824fe2cb
Create Date: 2026-07-12 02:24:26.001034
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '6b63f46afa3f'
down_revision: Union[str, None] = '5427824fe2cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('spam_confidence', sa.Float(), nullable=True))
    op.add_column('emails', sa.Column('spam_signals', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'spam_signals')
    op.drop_column('emails', 'spam_confidence')
    # ### end Alembic commands ###
