"""add_email_provider_fields

Revision ID: c320c152a427
Revises: d1814ba76736
Create Date: 2026-07-09 10:15:42.567381
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c320c152a427'
down_revision: Union[str, None] = 'd1814ba76736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('provider', sa.String(length=32), nullable=True))
    op.add_column('emails', sa.Column('provider_message_id', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'provider_message_id')
    op.drop_column('emails', 'provider')
    # ### end Alembic commands ###
