"""add_outlook_accounts

Revision ID: d1814ba76736
Revises: 1c92b7d1c0af
Create Date: 2026-07-09 09:39:50.775558
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd1814ba76736'
down_revision: Union[str, None] = '1c92b7d1c0af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outlook_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_type', sa.String(length=32), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('connected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outlook_accounts_user_id'), 'outlook_accounts', ['user_id'], unique=True)
    op.drop_constraint(op.f('gmail_accounts_user_id_key'), 'gmail_accounts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('gmail_accounts_user_id_key'), 'gmail_accounts', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_outlook_accounts_user_id'), table_name='outlook_accounts')
    op.drop_table('outlook_accounts')
    # ### end Alembic commands ###
